### ISSUE TITLE
Funcionalidades basicas

### ISSUE THREAD

**Issue by ElS50** [ElS50/Bloc_de_Notas_Tkinter#5]
a) Crear el área de texto
Usa ScrolledText para un área de texto con barra de desplazamiento.
Haz que el texto sea editable.
b) Guardar archivo
Usa el módulo filedialog para abrir un cuadro de diálogo de "Guardar".
Guarda el contenido del texto en el archivo seleccionado.
c) Abrir archivo
Usa filedialog para abrir archivos.
Carga el contenido del archivo en el área de texto.

**Comment by JrojasV22** [comment]
Completado
